//자유게시판
export const FETCH_FREE_BOARD_LIST = 'FETCH_FREE_BOARD_LIST'
export const FETCH_FREE_BOARD = 'FETCH_FREE_BOARD'
export const FETCH_FREE_BOARD_COMMENTS_LIST = 'FETCH_FREE_BOARD_COMMENTS_LIST'
//사진게시판
export const FETCH_PHOTO_BOARD_LIST = 'FETCH_PHOTO_BOARD_LIST'
export const FETCH_PHOTO_BOARD = 'FETCH_PHOTO_BOARD'
export const FETCH_PHOTO_BOARD_COMMENTS_LIST = 'FETCH_PHOTO_BOARD_COMMENTS_LIST'
export const FETCH_PHOTO_BOARD_LIKE = 'FETCH_PHOTO_BOARD_LIKE'
//영상게시판
export const FETCH_VIDEO_BOARD_LIST = 'FETCH_VIDEO_BOARD_LIST'
export const FETCH_VIDEO_BOARD = 'FETCH_VIDEO_BOARD'
export const FETCH_VIDEO_BOARD_COMMENTS_LIST = 'FETCH_VIDEO_BOARD_COMMENTS_LIST'
export const FETCH_VIDEO_BOARD_LIKE = 'FETCH_VIDEO_BOARD_LIKE'
