export default {
    userInfo: null,
    localBoards:[],
    localBoard: null,
    localComments: [],
    foreignBoards:[],
    foreignBoard: null,
    foreignComments: [],
    questionBoards:[],
    questionBoard: null,
    questionComments: [],
    complaintBoards:[],
    complaintBoard: null,
    complaintComments: [],
}