export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'

export const FETCH_AUTH = 'FETCH_AUTH'
export const FETCH_AUTH_LIST = 'FETCH_AUTH_LIST'


export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_BOARD_COMMENTS_LIST = 'FETCH_BOARD_COMMENTS_LIST'

export const FETCH_RESERVATION = 'FETCH_RESERVATION'
export const FETCH_RESERVATION_LIST = 'FETCH_RESERVATION_LIST'


/*
export const SET_IS_LOGIN = 'SET_IS_LOGIN'
export const COOKIE_SESSION = 'COOKIE_SESSION'
export const REMOVE_SESSION = 'REMOVE_SESSION'
export const REMOVE_IS_LOGIN = 'REMOVE_IS_LOGIN'

export const SET_MEMBER_NO = 'SET_MEMBER_NO' */
