export const FETCH_BRAND_CHECK_BOARD_LIST = 'FETCH_BRAND_CHECK_BOARD_LIST'
export const FETCH_BRAND_CHECK_BOARD = 'FETCH_BRAND_CHECK_BOARD'

export const FETCH_QUESTION_BOARD_LIST = 'FETCH_QUESTION_BOARD_LIST'
export const FETCH_QUESTION_BOARD = 'FETCH_QUESTION_BOARD'

export const USER_LOGIN = 'USER_LOGIN'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_SESSION = 'FETCH_SESSION'

export const FETCH_CHECK_BRAND_COMMENTS = 'FETCH_CHECK_BRAND_COMMENTS'
export const FETCH_CHECK_BRAND_COMMENT = 'FETCH_CHECK_BRAND_COMMENT'

export const FETCH_QUESTION_COMMENTS = 'FETCH_QUESTION_COMMENTS'
export const FETCH_QUESTION_COMMENT = 'FETCH_QUESTION_COMMENT'