export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'
export const FETCH_MEMBERAUTH_LIST = 'FETCH_MEMBERAUTH_LIST'
export const FETCH_MEMBERAUTH = 'FETCH_MEMBERAUTH'
export const FETCH_ROOM_LIST = 'FETCH_ROOM_LIST'
export const FETCH_ROOM = 'FETCH_ROOM'

export const FETCH_BOOK_READ = 'FETCH_BOOK_READ'

export const ALREADYS = 'ALREADYS'

export const FETCH_DATES_LIST = 'FETCH_DATES_LIST'
export const FETCH_USER_LIST = 'FETCH_USER_LIST'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_AUTH_LIST = 'FETCH_AUTH_LIST'

export const FETCH_BOOK_LIST = 'FETCH_BOOK_LIST'
export const FETCH_BOOK = 'FETCH_BOOK'
export const FETCH_RESERVE_LIST = 'FETCH_RESERVE_LIST'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'

export const CRAWL_START = 'CRAWL_START'
