export default {
    boards: [],
    board: null,
    members: [],
    member: null,
    users: [],
    user: null,
    auths: [],
    books: [],
    book: null,
    rooms: [],
    room: null,
    reserveDate: [],
    memberAuths: [],
    memberAuth: null,
    dates: [],
    memberRequest: null,
    alreadyCheckIn: [],
    bookReadDates: [],
    isLogin: false,
    isLoginError: false,
    lists: [],
    session: [],
}