export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'
export const FETCH_TIP_BOARD_LIST = 'FETCH_TIP_BOARD_LIST'
export const FETCH_TIP_BOARD = 'FETCH_TIP_BOARD'