export const FETCH_CAKE_LISTS = 'FETCH_CAKE_LISTS'
export const FETCH_BOOKING_LISTS = 'FETCH_BOOKING_LISTS'
export const FETCH_BOOKING_BOARD = 'FETCH_BOOKING_BOARD'
export const FETCH_BOARD_COMMENTS = 'FETCH_BOARD_COMMENTS'
