export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_PRODUCT_BOARD_LIST = 'FETCH_PRODUCT_BOARD_LIST'
export const FETCH_PRODUCT_BOARD = 'FETCH_PRODUCT_BOARD'


export const FETCH_JPA_BOARD_LIST = 'FETCH_JPA_BOARD_LIST'
export const FETCH_JPA_BOARD = 'FETCH_JPA_BOARD'

export const FETCH_JPA_BOARD_LIST1 = 'FETCH_JPA_BOARD_LIST1'
export const FETCH_JPA_BOARD1 = 'FETCH_JPA_BOARD1'

export const FETCH_JPA_BOARD_LIST2 = 'FETCH_JPA_BOARD_LIST2'
export const FETCH_JPA_BOARD2 = 'FETCH_JPA_BOARD2'

export const FETCH_JPA_BOARD_LIST3 = 'FETCH_JPA_BOARD_LIST3'
export const FETCH_JPA_BOARD3 = 'FETCH_JPA_BOARD3'


export const FETCH_JPA_BOARD_LIST4 = 'FETCH_JPA_BOARD_LIST4'
export const FETCH_JPA_BOARD4 = 'FETCH_JPA_BOARD4'




export const FETCH_BUSINESS_MEMBER = 'FETCH_BUSINESS_MEMBER'
export const CRAWL_START = 'CRAWL_START'
