//MEMBER
export const USER_LOGIN = 'USER_LOGIN'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_SESSION = 'FETCH_SESSION'

//NOTICE
export const FETCH_NOTICE_BOARD_LIST = 'FETCH_NOTICE_BOARD_LIST'
export const FETCH_NOTICE = 'FETCH_NOTICE'