//MEMBER
export const USER_LOGIN = 'USER_LOGIN'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_SESSION = 'FETCH_SESSION'

//NOTICE
export const FETCH_NOTICE_BOARD_LIST = 'FETCH_NOTICE_BOARD_LIST'
export const FETCH_NOTICE = 'FETCH_NOTICE'

//QNA
export const FETCH_QNA_BOARD_LIST = 'FETCH_QNA_BOARD_LIST'
export const FETCH_QNA = 'FETCH_QNA'

//COMMENT
export const FETCH_COMMENTS='FETCH_COMMENTS'
export const FETCH_COMMENT = 'FETCH_COMMENT'