export const FETCH_ALBUM_LIST = 'FETCH_ALBUM_LIST'
export const FETCH_ALBUM = 'FETCH_ALBUM' 

export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD' 

export const CRAWL_START = 'CRAWL_START'

export const FETCH_SESSION = 'FETCH_SESSION' 