export default {
    members: [],
    userPlans: [],
    inviteMember: [],
    dayContent: [],
    voteContents: [],
    userInfo: [],
    boardList: [],
    boardRead: null,
    boardReadImg: [],
    boardListComment: [],
    searchLikePlaceList: [],
    mapLikePlaceList: [],
    markLikePlaceList: [],
    placeLikeDayList: [],
    placeList: [],
    dayContentImg: [],
    myPage: null,
    savePlace: [],
    diaryList: [],
    diary: null,
    diaryImg: [],

}