export default {
    members: [],
    userPlans: [],
    inviteMember: [],
    dayContent: [],
    voteContents: [],
    userInfo: [],
    boardList: [],
    boardRead: null,
    boardReadImg: [],
    boardListComment: [],
    searchLikePlaceList: [],
    mapLikePlaceList: [],
    markLikePlaceList: [],
    placeLikeDayList: [],
}