export const FETCH_MEMBER = 'FETCH_MEMBER'

export const FETCH_FOOD_BOARD_LIST = 'FETCH_FOOD_BOARD_LIST'
export const FETCH_FOOD_BOARD = 'FETCH_FOOD_BOARD'

export const FETCH_BEST_FOOD_LIST = 'FETCH_BEST_FOOD_LIST'