export const FETCH_MEMBER = 'FETCH_MEMBER'
export const FETCH_COMMUNITY_BOARD_LIST = 'FETCH_COMMUNITY_BOARD_LIST'
export const FETCH_COMMUNITY_BOARD = 'FETCH_COMMUNITY_BOARD'
export const FETCH_COMMUNITY_COMMENTS_LIST = 'FETCH_COMMUNITY_COMMENTS_LIST'
export const FETCH_REVIEW_LIST = 'FETCH_REVIEW_LIST'
export const FETCH_REVIEW = 'FETCH_REVIEW'
export const FETCH_REVIEW_COMMENTS_LIST = 'FETCH_REVIEW_COMMENTS_LIST'

